#!/usr/bin/env bash
# One-time preparation of the publication web root and the go-publish
# prerequisites. Idempotent: safe to re-run, it only creates what is missing.
#
# Produces, under WEB_ROOT:
#   publish-setup.json     layout rules + server type for the whole site
#   package-feed.xml       RSS feed of published packages (FHIR registry reads this)
#   publication-feed.xml   RSS feed of published guides (human/reader consumption)
#   package-registry.json  generated by the publisher from the above
#   index.html             site landing page, linking both guides (if absent)
#   fhir/license.html      the page every history.html links as ../license.html
#   fhir/assets-hist/      local history.js + history-cm.js, so the history
#                          pages do not depend on hl7.org being reachable
#
# The four files above are written only when they do not already exist, so local
# edits and a hand-written landing page always survive a re-run.
#
# and, under PUBLICATION_DIR:
#   ig-history/   clone of HL7/fhir-ig-history-template
#   ig-registry/  clone of FHIR/ig-registry
#   templates/    site-specific history/index/search templates
#   temp/         publisher scratch space
#
# Usage: DHP_DATA=/srv/dhp setup-webroot.sh
# Env:   DHP_DATA (or WEB_ROOT and PUBLICATION_DIR), SITE_URL, SITE_ORG,
#        SITE_TITLE, WEB_SERVER_TYPE, CLONE_XML_JSON, PUBLISHER_JAR,
#        HIST_ASSETS_DIR, OFFLINE

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$HERE/lib/common.sh"

SITE_ORG="${SITE_ORG:-Ministry of Health of the Republic of Uzbekistan}"
SITE_TITLE="${SITE_TITLE:-Uzbekistan Digital Health Platform FHIR Implementation Guides}"
WEB_SERVER_TYPE="${WEB_SERVER_TYPE:-apache}"   # apache covers apache and nginx
CLONE_XML_JSON="${CLONE_XML_JSON:-false}"
OFFLINE="${OFFLINE:-0}"

mkdir -p "$WEB_ROOT" "$PUBLICATION_DIR" "$PUB_TEMPLATES" "$PUB_TEMP" "$PUBLISHER_CACHE" "$ZIPS_DIR" \
         "$DHP_DATA/txcache-seed"

clone_if_missing() {
  local url="$1" dir="$2"
  if [ -d "$dir/.git" ]; then
    log "$dir already present"
  elif [ "$OFFLINE" = "1" ]; then
    die "$dir missing and OFFLINE=1"
  else
    log "cloning $url -> $dir"
    git clone --depth 1 "$url" "$dir"
  fi
}

clone_if_missing https://github.com/HL7/fhir-ig-history-template.git "$IG_HISTORY"
clone_if_missing https://github.com/FHIR/ig-registry.git "$IG_REGISTRY"

# The customisable web templates. Taken from HL7/fhir-web-templates once, then
# edited in place for DHP styling; never re-copied over local edits.
if [ -z "$(ls -A "$PUB_TEMPLATES" 2>/dev/null)" ]; then
  tmp="$(mktemp -d)"
  log "seeding $PUB_TEMPLATES from HL7/fhir-web-templates"
  git clone --depth 1 https://github.com/HL7/fhir-web-templates.git "$tmp/wt"
  cp "$tmp"/wt/*template* "$PUB_TEMPLATES"/
  rm -rf "$tmp"
fi

# ------------------------------------------------------------ publish-setup.json
#
# layout-rules maps package ids to canonical URLs and web-root folders.
# uz.dhp.core        -> {1}=uz {2}=dhp {3}=core         -> https://dhp.uz/fhir/core         -> /fhir/core
# uz.dhp.integrations-> {1}=uz {2}=dhp {3}=integrations -> https://dhp.uz/fhir/integrations -> /fhir/integrations
# One rule therefore covers every current and future uz.dhp.* guide.
if [ ! -f "$WEB_ROOT/publish-setup.json" ]; then
  log "writing $WEB_ROOT/publish-setup.json"
  cat > "$WEB_ROOT/publish-setup.json" <<JSON
{
  "website": {
    "style": "fhir.layout",
    "url": "$SITE_URL",
    "server": "$WEB_SERVER_TYPE",
    "org": "$SITE_ORG",
    "search-template": "searchform.template.html",
    "index-template": "index.template",
    "clone-xml-json": $CLONE_XML_JSON
  },
  "feeds": {
    "package": "package-feed.xml",
    "publication": "publication-feed.xml"
  },
  "layout-rules": [
    {
      "npm": "uz.dhp.*",
      "canonical": "$SITE_URL/fhir/{3}",
      "destination": "/fhir/{3}"
    }
  ]
}
JSON
fi

# ----------------------------------------------------------------- RSS feeds
now="$(date -u '+%a, %d %b %Y %H:%M:%S GMT')"

write_feed() {
  local file="$1" title="$2" desc="$3" self="$4"
  [ -f "$file" ] && { log "$file already present"; return 0; }
  log "writing $file"
  cat > "$file" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:content="http://purl.org/rss/1.0/modules/content/"
     xmlns:fhir="http://hl7.org/fhir/feed"
     xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>$title</title>
    <description>$desc</description>
    <link>$SITE_URL/fhir</link>
    <generator>$SITE_ORG</generator>
    <lastBuildDate>$now</lastBuildDate>
    <atom:link href="$SITE_URL/$self" rel="self" type="application/rss+xml"/>
    <pubDate>$now</pubDate>
    <language>en</language>
    <ttl>600</ttl>
  </channel>
</rss>
XML
}

write_feed "$WEB_ROOT/publication-feed.xml" \
  "$SITE_TITLE" \
  "FHIR Implementation Guides published by the $SITE_ORG" \
  "publication-feed.xml"

write_feed "$WEB_ROOT/package-feed.xml" \
  "$SITE_TITLE - packages" \
  "FHIR Implementation Guide packages published by the $SITE_ORG" \
  "package-feed.xml"

# -------------------------------------------------------- package-registry.json
if [ ! -f "$WEB_ROOT/package-registry.json" ]; then
  prepare_publisher_jar_only() {
    mkdir -p "$(dirname "$PUBLISHER_JAR")"
    if [ ! -s "$PUBLISHER_JAR" ]; then
      [ "$OFFLINE" = "1" ] && die "no publisher.jar at $PUBLISHER_JAR and OFFLINE=1"
      curl -fsSL -o "$PUBLISHER_JAR" \
        https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar
    fi
  }
  prepare_publisher_jar_only
  log "generating $WEB_ROOT/package-registry.json"
  java -jar "$PUBLISHER_JAR" -generate-package-registry "$WEB_ROOT"
fi

# ------------------------------------------------------- history page assets
#
# The HL7 history template hard-codes two script tags to https://hl7.org/fhir/,
# and history.html is the landing page of every guide. Vendor both files so the
# page works on a network that cannot reach hl7.org; release.sh repoints the
# tags at this copy after each publication (localise_history_scripts).
#
# The ig-history clone is the fallback source because it is the upstream of the
# template itself, and it is already on disk by the time this runs.
mkdir -p "$HIST_ASSETS_DIR"
for js in history.js history-cm.js; do
  if [ -s "$HIST_ASSETS_DIR/$js" ]; then
    log "$HIST_ASSETS_DIR/$js already present"
    continue
  fi
  if [ "$OFFLINE" != "1" ] && curl -fsSL -o "$HIST_ASSETS_DIR/$js.part" "https://hl7.org/fhir/$js" 2>/dev/null; then
    mv "$HIST_ASSETS_DIR/$js.part" "$HIST_ASSETS_DIR/$js"
    log "vendored $js from hl7.org"
  elif [ -s "$IG_HISTORY/$js" ]; then
    rm -f "$HIST_ASSETS_DIR/$js.part"
    cp "$IG_HISTORY/$js" "$HIST_ASSETS_DIR/$js"
    log "vendored $js from the ig-history clone"
  else
    rm -f "$HIST_ASSETS_DIR/$js.part"
    warn "could not vendor $js - history.html will keep loading it from hl7.org"
  fi
done

# ------------------------------------------------------------- license page
#
# history.html links "../license.html" from the CC0 badge in the HL7 footer
# template, on every guide, at every published version. Nothing generates it, so
# it was a 404 on every history page. Written once and never overwritten, so the
# MOH can replace it with their own wording.
if [ ! -e "$WEB_ROOT/fhir/license.html" ]; then
  log "writing $WEB_ROOT/fhir/license.html"
  mkdir -p "$WEB_ROOT/fhir"
  cat > "$WEB_ROOT/fhir/license.html" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>License - $SITE_TITLE</title>
</head>
<body>
  <h1>License</h1>
  <p>
    The FHIR Implementation Guides on this site are published by the
    $SITE_ORG.
  </p>
  <p>
    Each guide states its own license and copyright on its home page and in the
    <code>jurisdiction</code> and <code>copyright</code> elements of its
    ImplementationGuide resource. Where a guide and this page disagree, the
    guide's own statement is the one that applies:
  </p>
  <ul>
    <li><a href="core/">UZ Core</a></li>
    <li><a href="integrations/">UZ Integrations</a></li>
  </ul>
  <p>
    HL7&#174;, FHIR&#174; and the FHIR flame Design mark are trademarks owned
    by Health Level Seven International. Material reproduced from the FHIR
    specification remains under the license of that specification.
  </p>
  <p><a href="../">Home</a></p>
</body>
</html>
HTML
fi

# --------------------------------------------------------------- site index
#
# The root of the site is not generated by anything: -go-publish maintains
# /fhir/<ig>/ and the feeds, never /index.html. It was left as a one-line
# placeholder, which is what a reader following a canonical URL up one level
# landed on. Written once and never overwritten.
if [ ! -e "$WEB_ROOT/index.html" ]; then
  log "writing $WEB_ROOT/index.html"
  cat > "$WEB_ROOT/index.html" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>$SITE_TITLE</title>
</head>
<body>
  <h1>$SITE_TITLE</h1>
  <p>
    FHIR Implementation Guides published by the $SITE_ORG.
    Each guide's own URL below always serves its current release.
  </p>
  <h2>Implementation Guides</h2>
  <ul>
    <li>
      <a href="fhir/core/">UZ Core</a>
      - the national base profiles.
      <a href="fhir/core/history.html">All versions</a>
    </li>
    <li>
      <a href="fhir/integrations/">UZ Integrations</a>
      - the integration profiles and operations.
      <a href="fhir/integrations/history.html">All versions</a>
    </li>
  </ul>
  <h2>Feeds</h2>
  <ul>
    <li><a href="package-feed.xml">package-feed.xml</a> - released packages, for the FHIR package registry</li>
    <li><a href="publication-feed.xml">publication-feed.xml</a> - published guides</li>
  </ul>
  <p><a href="fhir/license.html">License</a></p>
</body>
</html>
HTML
fi

cat <<EOF

Web root prepared at $WEB_ROOT
  publish-setup.json      $( [ -f "$WEB_ROOT/publish-setup.json" ] && echo ok )
  package-feed.xml        $( [ -f "$WEB_ROOT/package-feed.xml" ] && echo ok )
  publication-feed.xml    $( [ -f "$WEB_ROOT/publication-feed.xml" ] && echo ok )
  package-registry.json   $( [ -f "$WEB_ROOT/package-registry.json" ] && echo ok )
  index.html              $( [ -f "$WEB_ROOT/index.html" ] && echo ok )
  fhir/license.html       $( [ -f "$WEB_ROOT/fhir/license.html" ] && echo ok )
  fhir/assets-hist        $( [ -s "$HIST_ASSETS_DIR/history.js" ] && [ -s "$HIST_ASSETS_DIR/history-cm.js" ] && echo ok )
Publication workspace at $PUBLICATION_DIR
  ig-history              $IG_HISTORY
  ig-registry             $IG_REGISTRY
  templates               $PUB_TEMPLATES
  temp                    $PUB_TEMP
EOF
